# Generated by Django 4.2 on 2025-05-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenesdetencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='delito',
            options={'verbose_name_plural': 'Delitos'},
        ),
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'verbose_name_plural': 'Estado Civil'},
        ),
        migrations.AlterModelOptions(
            name='medidacautelar',
            options={'verbose_name_plural': 'Medidas Cautelares'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='sexo',
            options={'verbose_name_plural': 'Sexo'},
        ),
        migrations.AlterModelOptions(
            name='tribunal',
            options={'verbose_name_plural': 'Tribunales'},
        ),
    ]
